version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7.1-fpm
        volumes:
            - .:/var/www
            - ./config/php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www
    composer:
        image: composer:latest
        volumes:
            - .:/app
        command: install
